server:
  port: 8080 # 서버 포트 설정 (개발 환경에서는 기본적으로 8080 사용)

spring:
  config:
    activate:
      on-profle: dev # 이 설정이 'dev' 프로파일에서만 적용되도록 활성화
  jpa:
    show-sql: true # SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리를 보기 좋게 포맷팅
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시 테이블을 새로 생성

  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER # H2 인메모리 데이터베이스 사용 (개발 환경 전용)
  h2:
    console:
      enabled: true # H2 콘솔을 활성화 (웹 브라우저에서 DB 확인 가능)
logging:
  level:
    root: INFO # 개발 환경에서는 INFO 레벨까지 출력
  file:
    name: logs/dev-log.log # 개발 환경 로그를 'logs/dev-log.log' 파일에 저장

seoul:
  open:
    api:
      hot-spot:
        file-path: src/main/resources/static/area/서울시 주요 116장소명 목록.xlsx
